### ISSUE TITLE
Package __init__ files overwritten at compile

### ISSUE THREAD

**Issue by kubaraczkowski** [danielgtaylor/python-betterproto#168]
Hi,
Great library!

The generated `__init__.py` files that create packages are written (and empty) even if those were already present.
This creates a conflict with normally-non-empty `__init__` files, e.g. importing from subpackages.
For instance with a layout like this:

```
/
/src                                  # C code also using protobufs
/src/protobuf                  # protobuf definitions, shared between C and python
/src_py                            # python package root
/src_py/driver
/src_py/driver/__init__.py
/src_py/driver/driver.py
/src_py/driver/protobuf/ # compiled protobufs go here
```

and a generation command being:
`python -m grpc_tools.protoc -I ./src --python_betterproto_out=src_py/driver ./src/protobuf/*.proto
`
the file `./src_py/driver/__init__.py` gets overwritten

Perhaps the `__init__.py` generation could check if the file is empty?

**Comment by nat-n** [comment]
I see your point. I'm assuming you want to generate code directly inside `./src_py/driver` because your proto package structure is like `package protobuf;`? But betterproto puts an __init__.py outside of your top level package too...

Making the __init__.py generate conditional is tricky *in general* because replacing a contentful \__init__.py with an empty one could be a legit use case if content has been removed from the proto since the previous version.

I guess it would be better if it didn't do that. I'll tag this as an enhancement.

A plausible workaround might be to modify your package structure to not start with `protobuf`, and then generate code into `/src_py/driver/protobuf`.

**Comment by kubaraczkowski** [comment]
Thanks for your response.

Not sure if I we're talking the same here :) 

Indeed, the use-case is to generate the code into `src_py/driver/protobuf`. There the expected `__init__.py` gets placed, all nice and dandy.

The issue is that the compiler _also_ generates `src_py/driver/__init__.py` which is at top level of the `driver` package.


*However*, you gave me the right hint - it's due to the `-I` path of the compiler:
In my layout case this generates also the higher-level `__init__.py`
`python -m grpc_tools.protoc -I ./src --python_betterproto_out=src_py/driver ./src/protobuf/*.proto
`

but this doesn't:
`python -m grpc_tools.protoc -I ./src/protobuf --python_betterproto_out=src_py/driver/protobuf ./src/protobuf/*.proto
`

So the `__init__.py` files are generated at all higher levels detected by the difference of `-I` path and path to the `.proto` file itself. That's where the 'overwriting' issue can come to play.

**Comment by shaunco** [comment]
This overwriting issue is more pronounced in the v2.0.0b2 release due to v2 putting everything inside of `__init__.py` files instead of files named after the source proto file.

If `protoc` is invoked a single time with all possible input files, all is good. If `protoc` is invoked once per file, the overwriting happens. Who owns `__init__.py` when all .proto files are combined in to a single `__init__.py` file?

I experienced this behavior when I switched to using [buf.build](https://github.com/bufbuild/buf) instead of protoc directly, as buf.build seems to invoke `protoc` once per source file per [this response](https://github.com/bufbuild/buf/issues/202#issuecomment-733949460) from their team.

The attached [sample.zip](https://github.com/danielgtaylor/python-betterproto/files/5629039/sample.zip) demonstrates the issue. If you use `build-at-once.sh` all is good, if you use `build-one-file-at-a-time.sh` or `build-one-dir-at-a-time.sh` the overwriting occurs.

As you can see in the once per directory invocation output:
```
Invoking protoc for ./protos/pkg1...
Writing __init__.py
Writing protos/__init__.py
Writing protos/pkg1/__init__.py
Writing protos/pkg1/subpkg1/__init__.py

Invoking protoc for ./protos/pkg1/subpkg1...
Writing __init__.py
Writing protos/__init__.py
>>overwrite>> Writing protos/pkg1/__init__.py
Writing protos/pkg1/subpkg1/__init__.py

Invoking protoc for ./protos/pkg2...
Writing __init__.py
Writing protos/__init__.py
>>partial>> Writing protos/pkg1/__init__.py
>>partial>> Writing protos/pkg1/subpkg1/__init__.py
Writing protos/pkg2/__init__.py
Writing protos/pkg2/subpkg2/__init__.py

Invoking protoc for ./protos/pkg2/subpkg2...
Writing __init__.py
Writing protos/__init__.py
>>overwrite>> Writing protos/pkg2/__init__.py
Writing protos/pkg2/subpkg2/__init__.py
```

The `__init__.py` generated at the higher level (one up from the invoked directory) is where the overwrite occurs. Similarly, where pkg2 includes parts of pkg1, only those parts are written out on the `>>partial>>` lines.

[sample.zip](https://github.com/danielgtaylor/python-betterproto/files/5629039/sample.zip)
